In [ ]:
#exercise hwk3
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload() #this lets google colab choose a file from your computer (a window is opened with the choice)

Saving train.csv to train.csv

In [ ]:
df = pd.read_csv("train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
# Select only numerical columns before calculating the mean
numerical_cols = df.select_dtypes(include=np.number)
display(numerical_cols.mean())

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [ ]:
df[["Survived", "Pclass", "Age"]].mean()

Survived     0.383838
Pclass       2.308642
Age         29.699118
dtype: float64

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [ ]:
# Count non-null values in the 'Name' column
df1 = df[["Name", "Sex"]]
df1

                                                  Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [ ]:
df1['firstName'] = df1['Name'].str.split().str[-1]
df1

/tmp/ipython-input-2287404471.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['firstName'] = df1['Name'].str.split().str[-1]

                                                  Name     Sex firstName
0                              Braund, Mr. Owen Harris    male    Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female   Thayer)
2                               Heikkinen, Miss. Laina  female     Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female     Peel)
4                             Allen, Mr. William Henry    male     Henry
..                                                 ...     ...       ...
886                              Montvila, Rev. Juozas    male    Juozas
887                       Graham, Miss. Margaret Edith  female     Edith
888           Johnston, Miss. Catherine Helen "Carrie"  female  "Carrie"
889                              Behr, Mr. Karl Howell    male    Howell
890                                Dooley, Mr. Patrick    male   Patrick

[891 rows x 3 columns]

In [ ]:


most_common_female = df1[df1['Sex'] == 'female']['firstName'].mode()[0]
most_common_female

'Mary'

In [ ]:
most_common_male = df1[df1['Sex'] == 'male']['firstName'].mode()[0]
most_common_male

'John'

In [ ]:
df3 = df[["Name", "Sex", "Pclass"]]
df3['firstName'] = df1['firstName']
display(df3.groupby(["Sex", "Pclass"])["firstName"].value_counts())

/tmp/ipython-input-2809851205.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['firstName'] = df1['firstName']

Sex     Pclass  firstName
female  1       Elizabeth    3
                Edith        2
                Margaret     2
                "Nellie"     1
                "Suzette"    1
                            ..
male    3       Werner       1
                Yoto         1
                Youssef      1
                Yousseff     1
                Zenni")      1
Name: count, Length: 714, dtype: int64

In [ ]:
most_common_female_pclass1 = df3[(df3['Sex'] == 'female') & (df3['Pclass'] == 1)]['firstName'].mode()[0]
display(most_common_female_pclass1)
most_common_male_pclass1 = df3[(df3['Sex'] == 'male') & (df3['Pclass'] == 1)]['firstName'].mode()[0]
display(most_common_male_pclass1)
most_common_female_pclass2 = df3[(df3['Sex'] == 'female') & (df3['Pclass'] == 2)]['firstName'].mode()[0]
display(most_common_female_pclass2)
most_common_male_pclass2 = df3[(df3['Sex'] == 'male') & (df3['Pclass'] == 2)]['firstName'].mode()[0]
display(most_common_male_pclass2)
most_common_female_pclass3 = df3[(df3['Sex'] == 'female') & (df3['Pclass'] == 3)]['firstName'].mode()[0]
display(most_common_female_pclass3)
most_common_male_pclass3 = df3[(df3['Sex'] == 'male') & (df3['Pclass'] == 3)]['firstName'].mode()[0]
display(most_common_male_pclass3)

'Elizabeth'

In [ ]:
df[df['Age'] >44]

In [ ]:
df[(df['Age']< 44) & (df["Sex"]=="male")]

In [ ]:
df4 = df['Cabin'].value_counts()
df4

In [ ]:
df4 = df['Cabin'].value_counts()
display(df4.value_counts())

In [ ]:
# Find rows where any column has 'ABCDE'
mask = (df == 'C23 C25 C27').any(axis=1)

# Filter rows
result = df[mask]

print(result)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive